ProyectoAutoescuelaMvc/Models/Alumno.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProyectoAutoescuelaMvc.Models
{
    [Table("ALUMNO")]
    public class Alumno
    {
        [Key]
        [Column("AlumnoId")]
        public int AlumnoId { get; set; }


        [Column("Nombre")]
        public string Nombre { get; set; }


        [Column("Apellido")]
        public string Apellido {  get; set; }
        

        [Column("FechaNacimiento")]
        public DateTime FechaNacimiento { get; set; }


        [Column("VehiculoId")]
        public int VehiculoId { get; set; }


        [Column("AutoescuelaId")]
        public int AutoescuelaId { get; set; }


        [Column("SeccionId")]
        public int SeccionId { get; set; }


        [Column("ProfesorId")]
        public int ProfesorId { get; set; }
    }
}

ProyectoAutoescuelaMvc/Models/Documento.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace ProyectoAutoescuelaMvc.Models
{
    [Table("DOCUMENTO")]
    public class Documento
    {
        [Key]
        [Column("DocumentoId")]
        public int DocumentoId { get; set; }

        [Column("NombreDocumento")]
        public string NombreDocumento { get; set; }

        [Column("RutaArchivo")]
        public string RutaArchivo { get; set; }

        [Column("ContenidoDocumento")]
        public string ContenidoDocumento { get; set; }

        [Column("PDFData")]
        public byte[]? PDFData { get; set; }

        // Propiedades de navegación para los campos adicionales en la tabla de relación
        //[NotMapped] // Para evitar que Entity Framework intente mapear estas propiedades
        [Column("AlumnoId")]
        public int AlumnoId { get; set; }

        //[NotMapped]
        [Column("AutoescuelaId")]

        public int AutoescuelaId { get; set; }

        //[NotMapped]
        [Column("SeccionId")]
        public int SeccionId { get; set; }
    }
}

ProyectoAutoescuelaMvc/Models/SeccionComplementario.cs
namespace ProyectoAutoescuelaMvc.Models
{
    public class SeccionComplementario
    {
        public List<Seccion> Secciones { get; set; }
        public List<Documento> Documentos { get; set; }
        public List<Alumno> Alumnos { get; set; }
        public List<AlumnoCompleto> AlumnosCompletos { get; set; }
        public List<Profesor> Profesores { get; set; }
        public List<ProfesorCompleto> ProfesoresCompletos { get; set; }
        public List<Vehiculo> Vehiculos { get; set; }
        public List <VehiculoCategoria> VehiculoCategorias { get; set; }
        public List<Permiso> Permisos { get; set; }
    }
}

ProyectoAutoescuelaMvc/Controllers/AlumnosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProyectoAutoescuelaMvc.Models;
using ProyectoAutoescuelaMvc.Services;

namespace ProyectoAutoescuelaMvc.Controllers
{
    public class AlumnosController : Controller
    {
        private ServiceAutoescuela service;

        public AlumnosController(ServiceAutoescuela service)
        {
            this.service = service;
        }

        //[Authorize]
        //public async Task<IActionResult> Index()
        //{
        //    List<Alumno> alumnos = await this.service.GetAlumnosAsync();
        //    return View(alumnos);
        //}




    }
}

ProyectoAutoescuelaMvc/Controllers/SeccionComplementarioController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProyectoAutoescuelaMvc.Models;
using ProyectoAutoescuelaMvc.Services;

namespace ProyectoAutoescuelaMvc.Controllers
{
    public class SeccionComplementarioController : Controller
    {

        private ServiceAutoescuela service;

        public SeccionComplementarioController(ServiceAutoescuela service)
        {
            this.service = service;
        }

        //[Authorize]
        //public IActionResult Index()
        //{
        //    return View();
        //}


        [Authorize]
        public async Task<IActionResult> Alumnos()
        {
            List<AlumnoCompleto> alumnos = await this.service.GetAlumnosAsync();
            return View(alumnos);
        }

        [Authorize]
        public async Task<IActionResult> AlumnosDetails(int id)
        {
            AlumnoCompleto alumno = await this.service.DetallesAlumnoAsync(id);
            if (alumno == null)
            {
                return NotFound();
            }
            return View(alumno);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EliminarAlumno(int id)
        {
            try
            {
                // Llamar al método para eliminar el alumno en el servicio
                await service.EliminarAlumnoAsync(id);

                // Redirigir a la acción 'Alumnos' después de eliminar el alumno
                return RedirectToAction(nameof(Alumnos));
            }
            catch (Exception ex)
            {
                // Manejar cualquier excepción que pueda ocurrir
                ModelState.AddModelError(string.Empty, "Error al intentar eliminar al alumno: " + ex.Message);
                // Retornar la vista de detalles del alumno para mostrar el error
                return RedirectToAction(nameof(AlumnosDetails), new { id });
            }
        }


        [Authorize] 
        public IActionResult AlumnosCreate()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AlumnosCreate([Bind("Nombre,Apellido,FechaNacimiento,VehiculoId,AutoescuelaId,SeccionId,ProfesorId")] Alumno alumno)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await this.service.InsertarAlumnosAsync(alumno.Nombre, alumno.Apellido, alumno.FechaNacimiento, alumno.VehiculoId, alumno.AutoescuelaId, alumno.SeccionId, alumno.ProfesorId);
                    return RedirectToAction(nameof(Alumnos));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, "Error al intentar insertar al alumno: " + ex.Message);
                }
            }
            return View(alumno);
        }


        [Authorize]
        public async Task<IActionResult> VehiculosCategorias()
        {
            List<VehiculoCategoria> vehiculoscategorias = await this.service.GetVehiculoCategoria();
            return View(vehiculoscategorias);
        }


        [Authorize]
        public async Task<IActionResult> CargarCoches()
        {
            List<Coche> coches = await this.service.ObtenerCoches();
            return View(coches);
        }


        [Authorize]
        public async Task<IActionResult> Profesores()
        {
            List<Profesor> profesores = await this.service.GetProfesores();
            return View(profesores);
        }

        [Authorize]
        public IActionResult InsertarProfesor()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> InsertarProfesor([Bind("Nombre, Apellido, SeccionId")] ProfesorCompleto profesor)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await this.service.InsertarProfesor(profesor.Nombre, profesor.Apellido, profesor.SeccionId);
                    return RedirectToAction(nameof(Profesores));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, "Error al intentar insertar al profesor: " + ex.Message);
                }
            }
            return View(profesor);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EliminarProfesor(int id)
        {
            try
            {
                // Llamar al método para eliminar el alumno en el servicio
                await service.EliminarProfesor(id);

                // Redirigir a la acción 'Alumnos' después de eliminar el alumno
                return RedirectToAction(nameof(Profesores));
            }
            catch (Exception ex)
            {
                // Manejar cualquier excepción que pueda ocurrir
                ModelState.AddModelError(string.Empty, "Error al intentar eliminar al profesor: " + ex.Message);
                // Retornar la vista de detalles del alumno para mostrar el error
                return RedirectToAction(nameof(Profesores), new { id });
            }
        }


        [Authorize]
        public async Task<IActionResult> Documentos()
        {
            List<Documento> documentos = await this.service.GetDocumentos();
            return View(documentos);
        }


    }
}

ProyectoAutoescuelaMvc/Views/SeccionComplementario/Alumnos.cshtml
@model IEnumerable<ProyectoAutoescuelaMvc.Models.AlumnoCompleto>
@{
    ViewData["Title"] = "Alumnos";
}

<link rel="stylesheet" href="~/css/inicio.css" asp-append-version="true" />
<link rel="stylesheet" href="https://unpkg.com/gridjs/dist/theme/mermaid.min.css" />
<script src="https://unpkg.com/gridjs/dist/gridjs.production.min.js"></script>

<style>
    .btn-insertar-profesor {
        position: absolute;
        top: 20px;
        right: 20px;
    }
</style>


<a href="javascript:history.back()" class="btn-volver">
    <i class="fas fa-arrow-left" style="margin-right: 5px;"></i>
</a>

<h1 class="titulo-h1">Alumnos</h1>

<a asp-controller="SeccionComplementario" asp-action="AlumnosCreate" class="btn btn-primary btn-insertar-profesor">Nuevo Alumno</a>

<div id="grid"></div>

@section scripts {
    <script>
        new gridjs.Grid({
            columns: [
                {
                    name: 'alumnoId',
                    header: 'ID del Alumno',
                    hidden: true // Oculta la columna
                },
                { name: 'nombre', header: 'Nombre' },
                { name: 'apellido', header: 'Apellido' },
                {
                    name: '',
                    formatter: (_, row) => gridjs.html(`
                                <a href="#" class="btn btn-primary" onclick="redirectToDetails(${row.cells[0].data})">Ver Detalles</a>
                                <a href="#" class="btn btn-danger" onclick="confirmDelete(${row.cells[0].data})">Eliminar</a>
                            `)
                }
            ],
            data: @Html.Raw(Json.Serialize(Model)),
            pagination: true,
            search: true,
            sort: true,
            language: {
                'search': {
                    'placeholder': 'Buscar...'
                },
                'pagination': {
                    'previous': 'Anterior',
                    'next': 'Siguiente',
                    'showing': 'Mostrando del',
                    'results': () => 'resultados',
                    'to': 'al',
                    'of': 'de',
                    'An error happened while fetching the data': 'No se pueden mostrar los datos'
                },
                'noRecordsFound': 'No se encontraron resultados'
            }
        }).render(document.getElementById('grid'));

        function redirectToDetails(alumnoId) {
            window.location.href = `@Url.Action("AlumnosDetails", "SeccionComplementario")?id=${alumnoId}`;
        }

        function confirmDelete(alumnoId) {
            Swal.fire({
                title: '¿Estás seguro?',
                text: '¡No podrás revertir esto!',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: 'Sí, eliminarlo'
            }).then((result) => {
                if (result.isConfirmed) {
                    eliminarAlumno(alumnoId);
                }
            });
        }

        async function eliminarAlumno(alumnoId) {
            const response = await fetch(`/SeccionComplementario/EliminarAlumno?id=${alumnoId}`, {
                method: 'POST'
            });

            if (response.ok) {
                location.reload();
            } else {
                console.error('Error al eliminar el alumno');
            }
        }
    </script>
}

ProyectoAutoescuelaMvc/Views/SeccionComplementario/AlumnosCreate.cshtml
@model ProyectoAutoescuelaMvc.Models.Alumno

<link rel="stylesheet" href="~/css/inicio.css" asp-append-version="true" />


<a href="javascript:history.back()" class="btn-volver">
    <i class="fas fa-arrow-left" style="margin-right: 5px;"></i>
</a>


<h1 class="titulo-h1">Insertar Alumno</h1>

@if (ViewData["Mensaje"] != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewData["Mensaje"]
    </div>
}

<form asp-action="InsertarAlumnoCompleto" method="post">
    <div class="form-group">
        <label for="Nombre">Nombre:</label>
        <input type="text" id="Nombre" name="Nombre" class="form-control" required>
    </div>
    <div class="form-group">
        <label for="Apellido">Apellido:</label>
        <input type="text" id="Apellido" name="Apellido" class="form-control" required>
    </div>
    <div class="form-group">
        <label for="FechaNacimiento">Fecha de Nacimiento:</label>
        <input type="date" id="FechaNacimiento" name="FechaNacimiento" class="form-control" required>
    </div>
    <div class="form-group">
        <label for="VehiculoId">Vehículo ID:</label>
        <input type="text" id="VehiculoId" name="VehiculoId" class="form-control" required>
    </div>
    <div class="form-group">
        <label for="AutoescuelaId">Autoescuela ID:</label>
        <input type="text" id="AutoescuelaId" name="AutoescuelaId" class="form-control" required>
    </div>
    <div class="form-group">
        <label for="SeccionId">Sección ID:</label>
        <input type="text" id="SeccionId" name="SeccionId" class="form-control" required>
    </div>
    <div class="form-group">
        <label for="ProfesorId">Profesor ID:</label>
        <input type="text" id="ProfesorId" name="ProfesorId" class="form-control" required>
    </div>
    <div class="form-group">
        <label for="PermisoId">Permiso ID:</label>
        <input type="text" id="PermisoId" name="PermisoId" class="form-control" required>
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Insertar Alumno</button>
</form>

ProyectoAutoescuelaMvc/Views/SeccionComplementario/AlumnosDetails.cshtml
@model ProyectoAutoescuelaMvc.Models.AlumnoCompleto
<link rel="stylesheet" href="~/css/inicio.css" asp-append-version="true" />
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

@{
    ViewData["Title"] = "Detalles del Alumno";
}


<a style="text-decoration:none;" href="javascript:history.back()" class="btn-volver">
    <i class="fas fa-arrow-left" style="margin-right: 5px;"></i>
</a>

<h1 class="titulo-h1">Detalles del Alumno</h1>

<table class="table table-striped">
    <tr>
        <th>Nombre</th>
        <td>@Model.Nombre</td>
    </tr>
    <tr>
        <th>Apellido</th>
        <td>@Model.Apellido</td>
    </tr>
    <tr>
        <th>Fecha de Nacimiento</th>
        <td>@Model.FechaNacimiento</td>
    </tr>
    <tr>
        <th>Nombre de la Autoescuela</th>
        <td>@Model.NombreAutoescuela</td>
    </tr>
    <tr>
        <th>Nombre de la Sección</th>
        <td>@Model.NombreSeccion</td>
    </tr>
    <tr>
        <th>Nombre del Permiso</th>
        <td>@Model.NombrePermiso</td>
    </tr>
    <tr>
        <th>Nombre del Profesor</th>
        <td>@Model.NombreProfesor</td>
    </tr>
</table>

ProyectoAutoescuelaMvc/Views/SeccionComplementario/CargarCoches.cshtml
@model List<ProyectoAutoescuelaMvc.Models.Coche>
<link rel="stylesheet" href="~/css/inicio.css" asp-append-version="true" />

<a href="javascript:history.back()" class="btn-volver">
    <i class="fas fa-arrow-left" style="margin-right: 5px;"></i>
</a>

<h1 class="titulo-h1">Listado de Coches</h1>

<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                @* <th scope="col">ID</th> *@
                <th scope="col">Fecha Alta</th>
                @* <th scope="col">Fecha Baja</th> *@
                <th scope="col">Matrícula</th>
                @* <th scope="col">ITV</th> *@
                <th scope="col">Fecha Anterior ITV</th>
                <th scope="col">Fecha Próxima ITV</th>
                <th scope="col">Seguro</th>
                @* <th scope="col">Imagen</th> *@
                <th scope="col">Modelo</th>
                <th scope="col">Marca</th>
                @* <th scope="col">Vehículo ID</th> *@
            </tr>
        </thead>
        <tbody>
            @foreach (var coche in Model)
            {
                <tr>
                    @* <td>@coche.IdCoche</td> *@
                    <td>@coche.FechaAlta</td>
                    @* <td>@coche.FechaBaja</td> *@
                    <td>@coche.Matricula</td>
                    @* <td>@coche.ITV</td> *@
                    <td>@coche.FechaAnteriorITV</td>
                    <td>@coche.FechaProximaITV</td>
                    <td>@coche.Seguro</td>
                    @* <td>@coche.Imagen</td> *@
                    <td>@coche.Modelo</td>
                    <td>@coche.Marca</td>
                    @* <td>@coche.VehiculoId</td> *@
                </tr>
            }
        </tbody>
    </table>
</div>

ProyectoAutoescuelaMvc/Views/SeccionComplementario/Documentos.cshtml
@model IEnumerable<ProyectoAutoescuelaMvc.Models.Documento>

<link rel="stylesheet" href="~/css/inicio.css" asp-append-version="true" />

<a href="javascript:history.back()" class="btn-volver">
    <i class="fas fa-arrow-left" style="margin-right: 5px;"></i>
</a>

<style>
    .btn-insertar-documento {
        position: absolute;
        top: 20px;
        right: 20px;
    }

    .titulo-h1 {
        margin-top: 50px; /* Ajuste del margen superior para adaptarse al diseño */
    }
</style>

<a asp-action="InsertarDocumento" asp-controller="SeccionComplementario" class="btn btn-primary btn-insertar-documento">
    Insertar Documento
</a>

<h1 class="titulo-h1">Documentación</h1>

    <div class="table-responsive">
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>Nombre Documento</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var documento in Model)
                {
                    <tr>
                        <td>@documento.NombreDocumento</td>
                        <td><a asp-action="MostrarPDFenPagina" asp-controller="SeccionComplementario" class="btn btn-primary">Ver Documento</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>


<a class="btn btn-primary" asp-controller="SeccionComplementario" asp-action="MostrarPDFenPagina" target="_blank">Ver PDF en página</a>
<br />
<br />
<embed src="@Url.Action("MostrarPDFenPagina", "SeccionComplementario")" width="1000" height="700" type="application/pdf" />

@section scripts {
    <script>
        // Función para manejar el cambio en el elemento select
        document.getElementById('secciones').addEventListener('change', function () {
            var seccionId = this.value; // Obtener el valor seleccionado
            // Enviar una solicitud POST al servidor para guardar el valor en la sesión
            fetch('/Usuario/GuardarSeccionId', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded'
                },
                body: 'seccionId=' + encodeURIComponent(seccionId)
            })
                .then(response => {
                    // Actualizar la página para reflejar el cambio en la sesión
                    location.reload();
                })
                .catch(error => {
                    console.error('Error al actualizar la sesión:', error);
                });
        });
    </script>
}

ProyectoAutoescuelaMvc/Views/SeccionComplementario/InsertarProfesor.cshtml
@model ProyectoAutoescuelaMvc.Models.SeccionComplementario


@{
    ViewData["Title"] = "Insertar Profesor";
}

<link rel="stylesheet" href="~/css/inicio.css" asp-append-version="true" />


<a href="javascript:history.back()" class="btn-volver">
    <i class="fas fa-arrow-left" style="margin-right: 5px;"></i>
</a>

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            @if (TempData["SuccessMessage"] != null)
            {
                <div class="alert alert-success" role="alert">
                    @TempData["SuccessMessage"]
                </div>
            }
            else if (TempData["ErrorMessage"] != null)
            {
                <div class="alert alert-danger" role="alert">
                    @TempData["ErrorMessage"]
                </div>
            }

            <div class="card">
                <div class="card-header">
                    Insertar Profesor
                </div>
                <div class="card-body">
                    <form method="post">
                        <div class="form-group">
                            <label for="nombre">Nombre:</label>
                            <input type="text" class="form-control" id="nombre" name="nombre" required>
                        </div>
                        <div class="form-group">
                            <label for="apellido">Apellido:</label>
                            <input type="text" class="form-control" id="apellido" name="apellido" required>
                        </div>
                        <div class="form-group">
                            <label for="seccionId">Sección:</label>
                            <input type="number" class="form-control" id="seccion" name="seccion" required>
                        </div>
                        <br />
                        <button type="submit" class="btn btn-primary d-flex align-items-center justify-content-center">Insertar Profesor</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

ProyectoAutoescuelaMvc/Views/SeccionComplementario/Profesores.cshtml
@model IEnumerable<ProyectoAutoescuelaMvc.Models.Profesor>

<link rel="stylesheet" href="~/css/inicio.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/cards.css" asp-append-version="true" /> <!-- Agrega tu archivo de estilos para las tarjetas -->
@{
    ViewData["Title"] = "Profesores";

    // Obtener el ID de la sección seleccionada de la sesión
    var idSeccionSeleccionada = Context.Session.GetInt32("SeccionId");

    // Filtrar los profesores para eliminar duplicados
    var profesoresFiltrados = Model.GroupBy(p => p.ProfesorId)
                                   .Select(g => g.First())
                                   .ToList();
}

<a href="javascript:history.back()" class="btn-volver">
    <i class="fas fa-arrow-left" style="margin-right: 5px;"></i>
</a>

<style>
    .btn-insertar-profesor {
        position: absolute;
        top: 20px;
        right: 20px;
    }

    .titulo-h1 {
        margin-top: 50px; /* Ajuste del margen superior para adaptarse al diseño */
    }

    .content-card-inicio {
        margin-top: 10px; /* Ajuste del margen superior para adaptarse al diseño */
    }
</style>

<a asp-action="InsertarProfesor" asp-controller="SeccionComplementario" class="btn btn-primary btn-insertar-profesor">
    Insertar Profesor
</a>

<h1 class="titulo-h1">Profesores</h1>


<div class="container">
    <div class="card-inicio-container">
        @foreach (var profesor in profesoresFiltrados)
        {
            <div class="card-inicio">
                <img src="/images/Profesor.png" alt="Imagen de ejemplo">
                <div class="content-card-inicio">
                    <h2>@profesor.Nombre @profesor.Apellido</h2>
                    <button class="btn-eliminar btn btn-danger" onclick="eliminarProfesor(@profesor.ProfesorId)">Eliminar</button>
                </div>
            </div>
        }
    </div>
</div>

@section scripts {
    <script>
        document.getElementById('secciones').addEventListener('change', function () {
            var seccionId = this.value; // Obtener el valor seleccionado
            // Enviar una solicitud POST al servidor para guardar el valor en la sesión
            fetch('/Usuario/GuardarSeccionId', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded'
                },
                body: 'seccionId=' + encodeURIComponent(seccionId)
            })
                .then(response => {
                    // Actualizar la página para reflejar el cambio en la sesión
                    location.reload();
                })
                .catch(error => {
                    console.error('Error al actualizar la sesión:', error);
                });
        });

        function eliminarProfesor(profesorId) {
            // Mostrar el cuadro de diálogo de confirmación
            Swal.fire({
                title: '¿Estás seguro?',
                text: 'Una vez eliminado, no podrás recuperar este profesor.',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Sí, eliminar',
                cancelButtonText: 'Cancelar'
            }).then((result) => {
                if (result.isConfirmed) {
                    // Si el usuario confirma la eliminación, enviar la solicitud de eliminación al servidor
                    fetch(`/SeccionComplementario/EliminarProfesor?id=${profesorId}`, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json' // Agregar la cabecera Content-Type
                        }
                    })
                        .then(response => response.json())
                        .then(data => {
                            if (data.success) {
                                // Si la eliminación es exitosa, mostrar una alerta de éxito
                                Swal.fire('¡Eliminado!', 'El profesor ha sido eliminado.', 'success')
                                    .then(() => {
                                        // Después de cerrar la alerta, redirigir a la página de Profesores
                                        window.location.href = '/SeccionComplementario/Profesores';
                                    });
                            } else {
                                // Si hay un error, mostrar una alerta de error
                                Swal.fire('Error', data.error, 'error');
                            }
                        })
                        .catch(error => {
                            // Si hay un error en la solicitud, mostrar una alerta de error
                            console.error('Error al eliminar el profesor:', error);
                            Swal.fire('¡Eliminado!', 'El profesor ha sido eliminado.', 'success')
                            window.location.href = '/SeccionComplementario/Profesores';
                            // Swal.fire('Error', 'Se produjo un error al eliminar el profesor.', 'error');
                        });
                }
            });
        }

    </script>
}

ProyectoAutoescuelaMvc/Views/SeccionComplementario/VehiculosCategorias.cshtml
@model IEnumerable<ProyectoAutoescuelaMvc.Models.VehiculoCategoria>

<link rel="stylesheet" href="~/css/inicio.css" asp-append-version="true" />

<a href="javascript:history.back()" class="btn-volver">
    <i class="fas fa-arrow-left" style="margin-right: 5px;"></i>
</a>

<style>
    .btn-insertar-vehiculo {
        position: absolute;
        top: 20px;
        right: 20px;
    }

    .titulo-h1 {
        margin-top: 50px; /* Ajuste del margen superior para adaptarse al diseño */
    }
</style>

<a asp-action="InsertarVehiculo" asp-controller="SeccionComplementario" class="btn btn-primary btn-insertar-vehiculo">
    Insertar Vehículo
</a>

<h1 class="titulo-h1">Vehículos</h1>

@if (Model != null && Model.Any())
{
    <div class="container">
        <div class="card-inicio-container">
            @foreach (var categoria in Model)
            {
                <div class="card-inicio">
                    @if (categoria.CategoriaId == 1)
                    {
                        <a style="text-decoration: none;" href="@Url.Action("CargarCoches", "SeccionComplementario")" class="card-link">
                            <img src="/images/Coche.png" class="card-img-top" alt="Imagen Coche">
                            <div class="content-card-inicio">
                                <h2>@categoria.Nombre</h2>
                            </div>
                        </a>
                    }
                    else if (categoria.CategoriaId == 2)
                    {
                        <img src="/images/Moto.png" class="card-img-top" alt="Imagen Moto">
                        <div class="content-card-inicio">
                            <h2>@categoria.Nombre</h2>
                        </div>
                    }
                    else if (categoria.CategoriaId == 3)
                    {
                        <img src="/images/Ciclomotor.png" class="card-img-top" alt="Imagen Ciclomotor">
                        <div class="content-card-inicio">
                            <h2>@categoria.Nombre</h2>
                        </div>
                    }
                    else if (categoria.CategoriaId == 4)
                    {
                        <img src="/images/Camion.png" class="card-img-top" alt="Imagen Camión">
                        <div class="content-card-inicio">
                            <h2>@categoria.Nombre</h2>
                        </div>
                    }
                    else if (categoria.CategoriaId == 5)
                    {
                        <img src="/images/Autobus.png" class="card-img-top" alt="Imagen Autobús">
                        <div class="content-card-inicio">
                            <h2>@categoria.Nombre</h2>
                        </div>
                    }
                </div>
            }
        </div>
    </div>
}
else
{
    <p>No se encontraron categorías de vehículos.</p>
}